# Generated by Django 6.0.1 on 2026-02-02 02:02

import django.db.models.deletion
import wagtail.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_create_homepage'),
        ('wagtailimages', '0027_image_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='homepage',
            name='connect_text',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='homepage',
            name='connect_title',
            field=models.CharField(blank=True, default='Connect with Us', max_length=255),
        ),
        migrations.AddField(
            model_name='homepage',
            name='countdown_target',
            field=models.DateTimeField(blank=True, help_text='Next service time for the countdown timer', null=True),
        ),
        migrations.AddField(
            model_name='homepage',
            name='guest_header',
            field=models.CharField(blank=True, default='First Time Guests', max_length=255),
        ),
        migrations.AddField(
            model_name='homepage',
            name='hero_cta_text',
            field=models.CharField(blank=True, default='Join Us for Service', max_length=50),
        ),
        migrations.AddField(
            model_name='homepage',
            name='hero_image',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailimages.image'),
        ),
        migrations.AddField(
            model_name='homepage',
            name='hero_subtitle',
            field=models.CharField(blank=True, help_text='Executing the Mandate. Advancing the Kingdom. It is NOW!', max_length=255),
        ),
        migrations.AddField(
            model_name='homepage',
            name='hero_title',
            field=models.CharField(blank=True, help_text='High-impact hero title', max_length=255),
        ),
        migrations.AddField(
            model_name='homepage',
            name='salvation_prayer_text',
            field=wagtail.fields.RichTextField(blank=True),
        ),
        migrations.AddField(
            model_name='homepage',
            name='salvation_prayer_title',
            field=models.CharField(blank=True, default='The Salvation Prayer', max_length=255),
        ),
    ]
