# Generated by Django 6.0.1 on 2026-02-05 05:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_homepage_connect_text_homepage_connect_title_and_more'),
        ('wagtailcore', '0096_referenceindex_referenceindex_source_object_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='SiteSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('church_name', models.CharField(default="The Father's House, All Nations Church", max_length=255)),
                ('tagline', models.CharField(blank=True, default='Executing the Mandate. Advancing the Kingdom. It is NOW!', max_length=255)),
                ('service_times', models.CharField(blank=True, default='Sunday 9:00 AM – 1:30 PM', max_length=255)),
                ('location_line_1', models.CharField(blank=True, default='Gordon International School Hall,', max_length=255)),
                ('location_line_2', models.CharField(blank=True, default='Port Moresby', max_length=255)),
                ('google_maps_url', models.URLField(blank=True, default='https://maps.google.com')),
                ('facebook_url', models.URLField(blank=True, default='https://facebook.com/tfhanc')),
                ('copyright_text', models.CharField(blank=True, default="2026 The Father's House, All Nations Church. All Rights Reserved.", max_length=255)),
                ('site', models.OneToOneField(editable=False, on_delete=django.db.models.deletion.CASCADE, to='wagtailcore.site')),
            ],
            options={
                'verbose_name': 'Site Settings',
            },
        ),
    ]
